improve test and codebuild test bats

diff --git a/scripts/fbackup b/scripts/fbackup
--- a/scripts/fbackup
+++ b/scripts/fbackup
@@ -76,6 +76,11 @@ done
 
 [[ -n "${selected_files}" ]] && dotbare_backup "${selected_files}" "${action_command}"
 
+[[ ! -d "${DOTBARE_DIR}" ]] \
+  && echo "Could not locate your DOTBARE_DIR" \
+  && echo "Run dotbare finit or dotbare finit -u URL to initialise dotbare" \
+  && exit 1
+
 cd "${DOTBARE_TREE}"
 if [[ -n "${individual_file}" ]]; then
   selected_files=$(get_git_file "select files to backup" "raw")
