refactor(fstat): update arg handling

diff --git a/scripts/fstat b/scripts/fstat
--- a/scripts/fstat
+++ b/scripts/fstat
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
 #
 # interactive git status menu
-# allow staging ustaging actions
+# toggle stage and unstage
 #
 # @params
 # Globals
 #   ${mydir}: current directory of where the script is running
-#   ${selected_files}: selected file to stage or unstage
+#   ${selected_files}: raw selected file (with current git status prepend)
+#   ${selected_filenames}: bash array of names for the selected_files
 #   ${stage_file}: determine if current operation should be staging file or unstage
 # Arguments
-#   -h: show help message and exit
+#   -h|--help: show help message and exit
 
 set -e
 set -f
@@ -21,19 +22,23 @@ source "${mydir}"/../helper/git_query.sh
 function usage() {
   echo -e "Usage: dotbare fstat [-h] ...\n"
   echo -e "Display interactive git status menu"
-  echo -e "Stage, unstage, interactively\n"
+  echo -e "Toggle file stage/unstage interactively\n"
   echo -e "optional arguments:"
-  echo -e "  -h\t\tshow this help message and exit"
+  echo -e "  -h, --help\t\tshow this help message and exit"
 }
 
-while getopts ":h" opt; do
-  case "$opt" in
-    h)
+selected_filenames=()
+selected_files=""
+stage_file=""
+
+while [[ "$#" -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
       usage
       exit 0
       ;;
     *)
-      echo "Invalid option: ${OPTARG}" >&2
+      echo "Invalid option: $1" >&2
       usage
       exit 1
       ;;
@@ -41,9 +46,13 @@ while getopts ":h" opt; do
 done
 
 while :; do
-  selected_files=$(get_modified_file "select a file" "all" "raw")
+  selected_files=$(get_modified_file "select files to stage/unstage" "all" "raw")
   [[ -z "${selected_files}" ]] && break
+
   # check if current operation should stage file or unstage file
+  # if any file start with M but has char immediately follow it, new changes are made, stage file
+  # if any file start with a space or tab, the file is not staged, stage file
+  # otherwise, we unstage
   stage_file=$(echo "${selected_files}" | awk '{
     if ($0 ~ /^[A-Za-z][A-Za-z].*$/) {
       print "stage"
@@ -51,14 +60,14 @@ while :; do
       print "stage"
     }
   }')
-  selected_files=$(echo "${selected_files}" | awk -v home="${DOTBARE_TREE}" '{
-    print home "/" $2
-  }')
+
+  while IFS= read -r line; do
+    selected_filenames+=("${line}")
+  done < <(echo "${selected_files}" | awk -v home="${DOTBARE_TREE}" '{print home "/" $2}')
+
   if [[ -z "${stage_file}" ]]; then
-    # shellcheck disable=SC2086
-    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" reset --quiet HEAD ${selected_files}
+    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" reset --quiet HEAD "${selected_filenames[@]}"
   else
-    # shellcheck disable=SC2086
-    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" add ${selected_files}
+    /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" add "${selected_filenames[@]}"
   fi
 done
