refactor(funtrack): update arg handling and remove all ignored rules use bash arrays

diff --git a/scripts/funtrack b/scripts/funtrack
--- a/scripts/funtrack
+++ b/scripts/funtrack
@@ -39,63 +39,65 @@ function usage() {
 }
 
 track_type="untrack"
+selected_files=()
+confirm=""
 
-while getopts ":hsSy" opt
-do
-  case "$opt" in
-    s)
-      track_type="update"
+while [[ "$#" -gt 0 ]]; do
+  case "$1" in
+    -t|--temp)
+      track_type="temp"
+      shift
       ;;
-    S)
+    -r|--resume)
       track_type="retrack"
+      shift
       ;;
-    y)
+    -y|--yes)
       confirm='y'
+      shift
       ;;
-    h)
+    -h|--help)
       usage
       exit 0
       ;;
     *)
-      echo "Invalid option: ${OPTARG}" >&2
+      echo "Invalid option: $1" >&2
       usage
       exit 1
       ;;
   esac
 done
 
-selected_files=$(get_git_file "select files to untrack" | tr "\n" " ")
-[[ -z "${selected_files}" ]] && exit 1
+while IFS= read -r line; do
+  selected_files+=("${line}")
+done < <(get_git_file "select files to untrack")
+[[ "${#selected_files[@]}" -eq 0 ]] && exit 1
 
-
-if [[ "${track_type}" == "update" ]]; then
-  echo "(dryrun) dotbare update-index --assume-unchanged ${selected_files}"
+if [[ "${track_type}" == "temp" ]]; then
+  [[ -z "${confirm}" ]] && echo "(dryrun) dotbare update-index --assume-unchanged ${selected_files[@]}"
   [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Files will be temporarily stop being tracked for changes, continue?")
   [[ "${confirm}" != 'y' ]] && exit 1
-  # shellcheck disable=SC2086
-  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" update-index --assume-unchanged ${selected_files}
+  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" update-index --assume-unchanged "${selected_files[@]}"
   echo -e " "
   echo "Selected files are temporarily untracked by git, use -S to continue tracking changes."
   echo "dotbare funtrack -s is not the recommanded way to untrack files, although it won't delete"
   echo "the files on other machines, please refer to git update-index official"
   echo "documentation for more information"
 elif [[ "${track_type}" == "retrack" ]]; then
-  echo "(dryrun) dotbare update-index --no-assume-unchanged ${selected_files}"
+  [[ -z "${confirm}" ]] && echo "(dryrun) dotbare update-index --no-assume-unchanged ${selected_files[@]}"
   [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Files will resume being tracked by git, continue?")
   [[ "${confirm}" != 'y' ]] && exit 1
-  # shellcheck disable=SC2086
-  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" update-index --no-assume-unchanged ${selected_files}
+  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" update-index --no-assume-unchanged "${selected_files[@]}"
   echo " "
   echo "Selected files are being resumed for track by git."
   echo "dotbare funtrack -s not the recommanded way to untrack files, although it won't delete"
   echo "the files on other machines, please refer to git update-index official"
   echo "documentation for more information"
 else
-  echo "(dryrun) dotbare rm --cached ${selected_files}"
+  [[ -z "${confirm}" ]] && echo "(dryrun) dotbare rm --cached ${selected_files[@]}"
   [[ -z "${confirm}" ]] && confirm=$(get_confirmation "Untrack the selected files?")
   [[ "${confirm}" != 'y' ]] && exit 1 
-  # shellcheck disable=SC2086
-  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" rm --cached ${selected_files}
+  /usr/bin/git --git-dir="${DOTBARE_DIR}" --work-tree="${DOTBARE_TREE}" rm --cached "${selected_files[@]}"
   echo -e " "
   echo "Selected files are being untracked by git, make sure to run dotbare fbackup"
   echo "on your other systems. When other system pull down this change, selected files"
