test(fupgrade): update test to reflect changes

diff --git a/scripts/fupgrade b/scripts/fupgrade
--- a/scripts/fupgrade
+++ b/scripts/fupgrade
@@ -20,7 +20,7 @@ while [[ "$#" -gt 0 ]]; do
       exit 0
       ;;
     *)
-      echo "Invalid option: ${OPTARG}" >&2
+      echo "Invalid option: $1" >&2
       usage
       exit 1
       ;;
